### ISSUE TITLE
missing \fi in maketitle

### ISSUE THREAD

**Issue by u-fischer** [SFr682k/fancyhandout#2]
```
\documentclass{fancyhandout}
\title{blub}
\begin{document}
\maketitle
\end{document}
```

gives

```
! Incomplete \ifx; all text was ignored after line 4.
<inserted text> 
                \fi 
```

**Comment by SFr682k** [comment]
Thanks for reporting this error and it is quite embarassing that I didn't find this error while beta testing.  

The problem should be fixed with PR #1 (thanks for Sébastien Le Callonnec <@tychobrailleur> for providing the patch), I'll merge this and upload the patched version to CTAN as soon as possible.
